### PR TITLE
[SKIP CI] Describe fix for installation on CoreOS

### PR DESCRIPTION
**Pull request by spawnia**
Documents a fix for the issue #1924

### CODE REVIEW

**Comment by spawnia** [comment]
Documents a fix for the issue #1924

**Comment by govint** [comment]
Looks good, please merge once CI is green.

**Comment by spawnia** [comment]
I can not do anything about CI, my commit only changed the docs so i am pretty sure it did not cause CI to fail.

**Comment by shuklanirdesh82** [comment]
It is a document change, CI run is not necessary so merging this now as there is an approval https://github.com/vmware/vsphere-storage-for-docker/pull/2076#issuecomment-373124560

**Pull request merged**
